// Copyright 2017-2022 @zzcwoshizz/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @zzcwoshizz/dev

export const packageInfo = { name: '@zzcwoshizz/dev', path: 'auto', type: 'auto', version: '0.0.0' };
