name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.repository == 'zzcwoshizz/dev'
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install deps
        run: |
          yarn install --immutable | grep -v 'YN0013'

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn z-dev-bump-version
          publish: yarn z-ci-ghact-release
